### PR TITLE
Bump auth library

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Related: https://github.com/openshiftio/openshift.io/issues/4399

**Comment by msrb** [comment]
Let's merge this and let E2E tests verify it...

**Comment by ppitonak** [comment]
@msrb how fast will it get to prod-preview?

**Comment by msrb** [comment]
@ppitonak it should land there in ~20 minutes: https://ci.centos.org/view/Devtools/job/devtools-fabric8-analytics-server-f8a-build-master/227/

**Pull request merged**
