### PR TITLE
chore: Remove v1 endpoints and related functionalities

### PR DESCRIPTION
**Pull request by sawood14012**
Cleanup v1 api code https://issues.redhat.com/browse/APPAI-1660

### CODE REVIEW

**Review by arajkumar — APPROVED** [review]
lgtm

Make sure that blackbox monitoring now points to v2 or base url.

**Review by prashbnair — APPROVED** [review]

**Comment by prashbnair** [comment]
@sawood14012 Lets make sure that there is no regression with the V2 api's.

**Review by arajkumar — CHANGES_REQUESTED** [review]
@sawood14012 , `/api/v1/submit-feedback` is still used from UI. You shouldn't remove that.

**Comment by prashbnair** [comment]
@sawood14012 the only way to figure out if we are going to have any regression will be to have a testing session with the whole team before rolling this out. Please plan for this after it is merged into staging.

**Comment by arajkumar** [comment]
@sawood14012 , can you please remove v1 api specs as well?

**Review by arajkumar — APPROVED** [review]
lgtm

**Pull request merged**
