### PR TITLE
refactor:removing user management code moved to utils

### PR DESCRIPTION
**Pull request by prashbnair**

### CODE REVIEW

**Comment by prashbnair** [comment]
Continuation of https://github.com/fabric8-analytics/fabric8-analytics-utils/pull/63

Removal of the common code from this repo

**Review by yzainee — APPROVED** [review]
I just see that now its referring to the util's section rather than api server code directly.

**Review by deepak1725 — APPROVED** [review]
LGTM

**Review by dgpatelgit — APPROVED** [review]
lgtm

**Pull request merged**
