### PR TITLE
Api endpoint bydate and ecosystem

### PR DESCRIPTION
**Pull request by Avni-Sharma**

### CODE REVIEW

**Comment by sunilk747** [comment]
[test]

**Comment by Avni-Sharma** [comment]
[test]

**Comment by Avni-Sharma** [comment]
[test]

**Comment by sunilk747** [comment]
[test]

**Comment by Avni-Sharma** [comment]
[test]

**Comment by tisnik** [comment]
Are we going to work on this patch? It has many flaws, not sure whether it is a good approach to invert time in in. WDYT?

**Pull request closed without merging**
