### PR TITLE
Removed unused API endpoints.

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**
All but the following API endpoints are currently being maintained. Hence, the cleanup has been carried out:

```
        "/api/v1",
        "/api/v1/component-analyses/<ecosystem>/<package>/<version>",
        "/api/v1/component-search/<package>",
        "/api/v1/schemas",
        "/api/v1/schemas/<collection>",
        "/api/v1/schemas/<collection>/<name>",
        "/api/v1/schemas/<collection>/<name>/<version>",
        "/api/v1/stack-analyses",
        "/api/v1/stack-analyses/<external_request_id>",
        "/api/v1/stack-analyses/by-origin/<origin>",
        "/api/v1/system/version",
        "/api/v1/user-feedback",
        "/api/v1/liveness",
        "/api/v1/readiness:
``` 

The endpoint `/api/v1/component-search/<package>` was previously published as `/api/v1/package-search`. Also, this new endpoint is now gated by SSO based authentication. @invincibleJai @arunkumars08, all client references for that endpoint will have to be changed to reflect the new name.

### CODE REVIEW

**Comment by jpopelka** [comment]
- The change would mean removing all [integration tests features](https://github.com/fabric8-analytics/fabric8-analytics-common/tree/master/integration-tests/features) we currently have since all they test is
  - /api/v1/ecosystems
  - /api/v1/packages
  - /api/v1/analyses/\<ecosystem>/\<package>/\<version>
  - /api/v1/versions/\<ecosystem>/\<package>
- Try `pip3 install pyflakes; pyflakes bayesian/api_v1.py` to find out which imports are now unused.

cc @bkabrda what do you think about the first point ?

**Comment by samuzzal-choudhury** [comment]
@jpopelka we are not planning to maintain those endpoints any more. I removed the related integrated tests too.

Let me check unused imports.

**Comment by bkabrda** [comment]
@jpopelka yes, you're correct. I think @pkajaba and @msrb were working on some integration tests, but I can't see any PRs. I'd definitely prefer having at least 1 basic integration test that verifies that the system is running (while not using the above endpoints) before merging this. Also, these old integration tests will need to get removed first, otherwise this will break all builds.

**Comment by samuzzal-choudhury** [comment]
@jpopelka @bkabrda as I mentioned earlier, I cleaned up test_api_v1.py. And that does not have any test corresponding to removed endpoints. The integration tests can be enhanced to include existing endpoints in another PR.

**Comment by pkajaba** [comment]
@samuzzal-choudhury @bkabrda I have WIP PR in old repository which I have to transfer here. It is supposed to test just `"/api/v1/stack-analyses"`.

**Comment by samuzzal-choudhury** [comment]
@pkajaba please wait for this PR to get merged. CC: @jpopelka @bkabrda

**Comment by pkajaba** [comment]
@samuzzal-choudhury you cleaned `test_api_v1.py` but removed endpoints are tested in integration tests too.

**Comment by samuzzal-choudhury** [comment]
@pkajaba got that. Is your PR still in progress?

**Comment by pkajaba** [comment]
@samuzzal-choudhury I have implemented posting manifest files to endpoint but I am not able to compare results because endpoint does not return correct info when it is running on docker-compose.

**Comment by samuzzal-choudhury** [comment]
@jpopelka commit b32eed6ec8b278c4ec7cc86165cddb06673e7571 has got the unused imports removed.

**Comment by pkajaba** [comment]
@samuzzal-choudhury integration tests are in common repo.

**Comment by samuzzal-choudhury** [comment]
@bkabrda @pkajaba can we suppress the integration tests for server until the integration tests are sorted out? I really need this PR to go through.

**Comment by jpopelka** [comment]
[test this]

**Comment by samuzzal-choudhury** [comment]
@jpopelka the PR looks all set to go :-)

**Comment by samuzzal-choudhury** [comment]
@jpopelka thanks for reviewing and merging.

**Pull request merged**
