### PR TITLE
Remove unused _approved_licenses.py

### PR DESCRIPTION
**Pull request by jpopelka**
While working on https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/56 I found this [bayesian/_approved_licenses.py](https://github.com/fabric8-analytics/fabric8-analytics-server/blob/master/bayesian/_approved_licenses.py).

Trying to see what's the history behind it, it led me to my local clone of ancient cucos repo, but even there I was not able to find out what we were using it for.

But I doubt we need it anymore.

### CODE REVIEW

**Comment by samuzzal-choudhury** [comment]
LGTM @jpopelka. Can you confirm whether or not forms.py and filters.py become a part of this cleanup? Those two are also unused.

**Comment by jpopelka** [comment]
You're right @samuzzal-choudhury 

I've updated the change.

**Comment by samuzzal-choudhury** [comment]
Build has failed. Otherwise, everything LGTM :-)

**Comment by jpopelka** [comment]
fixed

**Pull request merged**
