### PR TITLE
WIP: Rename bayesian/ to f8a_server/

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by pkajaba** [comment]
From grepping your branch there are still some traces of bayesian (README, tests, migrations). Is it OK?

**Comment by samuzzal-choudhury** [comment]
@jpopelka why is this change required? And what happens to my PR https://github.com/fabric8-analytics/fabric8-analytics-server/pull/8? CC: @bkabrda

**Comment by jpopelka** [comment]
Marking as WIP until #8 is merged.

**Comment by samuzzal-choudhury** [comment]
@jpopelka thanks.

**Comment by jpopelka** [comment]
Closing, see #45

**Pull request closed without merging**
