### PR TITLE
Set stack analyses v2 as the default /stack-analyses endpoint

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**

### CODE REVIEW

**Comment by msrb** [comment]
Waiting for green from Jenkins.

**Comment by msrb** [comment]
[test this]

**Comment by samuzzal-choudhury** [comment]
[test this]

**Comment by samuzzal-choudhury** [comment]
[test this]

**Comment by msrb** [comment]
👍 let's test this in staging 😉

**Comment by samuzzal-choudhury** [comment]
@msrb @miteshvp 👍

**Pull request merged**
