### PR TITLE
chore: User caching.

### PR DESCRIPTION
**Pull request by jparsai**
Created new API to create user cache in PVC. API will be called from daily reports to update the cache.

### CODE REVIEW

**Review by yzainee — APPROVED** [review]
LGTM

**Review by yzainee — CHANGES_REQUESTED** [review]
In template you need to add the secrets

**Comment by yzainee** [comment]
example:
- name: SNYK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: snyk-secrets
                      key: token

**Comment by jparsai** [comment]
> In template you need to add the secrets
I am using an existing secret.
https://github.com/fabric8-analytics/fabric8-analytics-server/blob/a1e2e0a2eaaf94fc2055251c9ec36610503f527b/openshift/template.yaml#L129

**Review by yzainee — APPROVED** [review]

**Pull request merged**
