### PR TITLE
[WIP]dependecyingestertask added for GA task

### PR DESCRIPTION
**Pull request by vasulakkaraju**
dependency ingester task added with test commit id from vasulakkaraju/fabric8-analytics-worker

### CODE REVIEW

**Comment by abs51295** [comment]
[test]

**Comment by ravsa** [comment]
[test]

**Comment by ravsa** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by vasulakkaraju** [comment]
[test]

**Comment by abs51295** [comment]
[test]

**Comment by vasulakkaraju** [comment]
Closing this PR,as these changes are no more required.

**Pull request closed without merging**
