### PR TITLE
Better disable authentication testing

### PR DESCRIPTION
**Pull request by tisnik**
in the docker_compose.yml, the setting of DISABLE_AUTHENTICATION to 0 nor "0" nor "" does not work because the code actually test the existence of this variable, not the content

### CODE REVIEW

**Comment by tisnik** [comment]
[test this]

**Comment by fridex** [comment]
BTW worth to unify this across services - jobs service has different idion https://github.com/fabric8-analytics/fabric8-analytics-jobs/blob/master/f8a_jobs/defaults.py#L18

**Comment by tisnik** [comment]
@fridex I'll look at f8a_jobs as well as I feel it is better to support all usual options - numeric 1/0 and booleans True/False, true/false as well (our yml files are a bit inconsistent here)

**Comment by fridex** [comment]
> @fridex I'll look at f8a_jobs as well as I feel it is better to support all usual options - numeric 1/0 and booleans True/False, true/false as well (our yml files are a bit inconsistent here)

Not needed anymore, I've already done that in https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/106

**Pull request merged**
